### ISSUE TITLE
Scouting questions for integrating apt2ostree into a compiling custom software to booting in PXE workflow

### ISSUE THREAD

**Issue by Mek101** [stb-tester/apt2ostree#14] opened 2022-06-05 11:23 UTC
I'm part of a small association dedicated to recycling computers. Among our projects, we wanted to port our hard disk wiper machine to boot a custom software system based off linux via PXE to do the wiping.
So far I'm still very in much in the "scouting" phase, and I was wondering if `apt2ostree` was suitable to be integrated in a workflow of this kind:

1. Build our wiper software with cargo (rust package manager)
2. Prepare the debian rootfs
3. Put our built software and configuration into it
4. Apply PXE modifications(?)
5. Commit everything into ostree
6. Build a squashfs image from the rootfs

The fact that `apt2ostree` operates as a library seems to suggest that it should be possible to separate the build and commit phases?
I was also wondering if apt2ostree can be configured to build a rootfs already suited for PXE.

Thank you for your time :-)

**Comment by wmanley** [comment] 2022-06-10 14:55
Thanks for your interest.

I've not played with PXE before.  In terms of your workflow I think apt2ostree could help with 2, 3 and 5.  Note: The way apt2ostree works there is no separate 5 step. We import individual debian packages as ostree commits and keep it that way throughout the build process.  You can learn more here: https://lwn.net/Articles/821367/ .

We created apt2ostree because we had some specific problems that the existing tools didn't help with. Things like:

* Functional reproducibility and tracking of dependencies - solved by lockfiles
* Build system integration for fast iteration - we create and store many many rootfses, and deploy complete rootfses as part of our development workflow - so it needs to be fast.  See the talk about metadata-only operations in the above article.  To achieve this being able to build incrementally is important - see my note below about squashfs.
* Ability to store many versions of our rootfs cheaply - solved by committing files into ostree early, and storing rootfses as ostree commits.

apt2ostree might be suitable for your use case if you have some of the same problems that you want to solve. If not you might find using the more standard upstream tools like `debootstrap` to be more appropriate.  In particular - if the last step in your build is constructing a whole squashfs image from scratch you may find the apt2ostree doesn't offer many benefits.

One other warning: We're happy if you use this project, but we mostly maintain it to be used with our internal build system - so we don't have much infrastructure to support other users - like a release process, backwards compatibility, documentation, etc.  We released it as a demonstration of certain ideas that we wanted to spread.  That said - it does work well for us, and there's little churn in practice.

I'm going to close this for now as I don't think there's any outstanding action here, but feel free to reply in the comments.

**Closed as completed by wmanley** 2022-06-10 14:55 UTC
